config/routes.rb
Rails.application.routes.draw do
  get 'home/index', as: :home
  get 'home/search', as: :search
  get 'home/about', as: :about

  root 'home#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  include Elasticsearch::Model

  paginates_per 15

  def self.search_by_ingredients(query)
    search(
      query: {
        multi_match: {
          query: query,
          fuzziness: 2,
          fields: [:name, 'ingredients^10', :description],
          minimum_should_match: '70%',
          cutoff_frequency: 0.1
        }
      }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def search
    @query = params[:query].presence || '*'

    @recipes = Recipe.search_by_ingredients(@query).page(params[:page])
    respond_to do |format|
      if request.xhr?
        if params[:page]
          format.html { render :partial => 'recipes_list' }
        else
          format.html { render layout: false }
        end
      else
        format.html { render layout: true }
      end
    end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def query_value(query)
    query == '*' ? '' : query
  end

  def cook_mins(recipe)
    cook_time = recipe.cookTime
    if cook_time
      mins = cook_time.scan(/\d+M/).first
      hours = cook_time.scan(/\d+H/).first
      if mins or hours
        cook_mins = (mins ? mins.chomp.to_i : 0)
        cook_mins = cook_mins + (hours ? hours.chomp.to_i : 0) * 60
        "<span class='value'>#{cook_mins}</span><span class='label'>min</span>"
      end
    end
  end
end

app/views/home/_recipes_list.html.erb
<div class="recipe-boxes">
  <% @recipes.each do |recipe| %>
    <div class="recipe-box">
      <a href="<%=recipe.url%>" target="blank">
        <span class="image-wrapper">
          <span class="image" style="background-image: url(<%=recipe.image%>);"></span>
          <span class="time-icon">
            <%=raw cook_mins(recipe)%>
          </span>
        </span>
        <h3><%=recipe.name%></h3>
        <div class="ingredients"><%= simple_format recipe.ingredients%></div>
      </a>
    </div>
  <% end %>
</div>
<div class="more_recipes"><%= link_to_next_page @recipes, 'Load more Recipes', class: 'pure-button pure-button-primary', :params => {:query => query_value(@query)} %></div>

app/views/home/about.html.erb
<header class="site-header static-header">
  <div class="pure-g">
    <h2><%= link_to 'leancook', root_path, class: 'pure-menu-heading' %></h2>
</header>

<div id="content" class="site-content">
  <div class="pure-g main-content static-content">
  	<h1>About leancook</h1>
  	<p>
  		<strong>Leancook</strong> is a project created with love and some beer for the <a href="http://railsrumble.com">Rails Rumble 2014</a>.
		<img src="https://d4nnn7wspfa3h.cloudfront.net/rails-rumble-badge-2014.png"></img>
  	</p>
  	<p>
  		The code <a href="https://github.com/railsrumble/leancook">on GitHub</a>.
  	</p>
  	<h2>Team Members</h2>
		<ul>
			<li><a href="http://twitter.com/jrubr">Javier Rubio</a></li>
			<li><a href="http://twitter.com/dani_latorre">Dani Latorre</a></li>
			<li><a href="http://twitter.com/leptom">Rafa García</a></li>
			<li><a href="http://twitter.com/superwillyfoc">Guillermo Latorre</a></li>
		</ul>
		<h2>Vote for us. Yes, you can!</h2>
		<p>You can be one of the millions who are voting us to win the <a href="http://railsrumble.com">Rails Rumble 2014</a> only clicking on the banner at the bottom of this page :)
		</p>

  </div><!-- .static-content -->
</div><!-- .site-content -->

app/views/home/index.html.erb
<header class="site-header home-header">
  <div class="pure-g" id="home_header">
    <div class="pure-u-1">
      <h1><%= link_to 'leancook', root_path, class: 'pure-menu-heading' %></h1>
    </div><!-- .pure-u-1 -->
  </div><!-- .pure-g -->

  <div class="pure-g" id="search_header" style="display:none">
    <h2><%= link_to 'leancook', root_path, class: 'pure-menu-heading' %></h2>

    <div class="header-search-form">
      <%= form_tag search_path, method: 'get', class: 'pure-form', id: 'search_form' do %>
        <div class="text-field">
          <%= text_field_tag :query, query_value(@query), placeholder: 'Write your ingredients', class: 'pure-input' %>
        </div>
        <div class="submit-field">
          <%= button_tag 'Search', class: 'pure-input-3 pure-button pure-button-secondary' %>
        </div>
      <% end %>
    </div>
  </div><!-- .pure-g -->
</header>
<div id="content" class="site-content">
  <div class="pure-g main-content home-search">
    <div class="pure-u-1">
      <%= form_tag search_path, method: 'get', class: 'pure-form pure-g', id: 'search_form_home' do %>
        <div class="pure-u-1 pure-u-md-1-3">
          <h2>What's in your fridge?</h2>
        </div>
        <div class="home-search-form">
          <div class="text-field pure-u-1 pure-u-md-1-3">
            <%= text_field_tag :query, '', placeholder: 'Write here your ingredients', class: 'pure-input', id: 'query_home' %>
          </div>
          <div class="example-field">
            Separate the ingredients using spaces. <strong>Example: potato egg oil</strong>
          </div>
          <div class="submit-field pure-u-1 pure-u-md-1-3 buttons">
            <%= button_tag 'Search recipes', class: 'pure-input-3 pure-button pure-button-primary' %>
          </div>
        </div><!-- .home-search-form -->
      <% end %>
    </div><!-- .pure-u-1 -->
  </div><!-- .pure-g.home-search -->
    <footer class="pure-g site-footer site-footer-home">
    <nav class="footer-navigation">
      <ul>
        <li>
          <a href="/home/about">about leancook</a>
        </li>
      </ul>
    </nav>
  </footer>
</div>

app/views/home/search.html.erb
<%unless request.xhr?%>
  <header class="site-header search-header">
    <div class="pure-g">
      <h2><%= link_to 'leancook', root_path, class: 'pure-menu-heading' %></h2>

      <div class="header-search-form">
        <%= form_tag search_path, method: 'get', class: 'pure-form', id: 'search_form' do %>
          <div class="text-field">
            <%= text_field_tag :query, query_value(@query), placeholder: 'Write your ingredients', class: 'pure-input' %>
          </div>
          <div class="submit-field">
            <%= button_tag 'Search', class: 'pure-input-3 pure-button pure-button-secondary' %>
          </div>
        <% end %>
      </div>
    </div><!-- .pure-g -->
  </header>
  <div id="content" class="site-content">
<%end%>

  <div class="pure-g main-content search-content">
    <h1 class="search-title">Recipes with "<%= query_value(@query) %>"</h1>
    <div id="recipes_list">
      <%=render :partial => "recipes_list" %>
    </div><!-- .recipe-boxes -->
  </div>
<%unless request.xhr?%>
  </div>
<%end%>

<footer class="pure-g site-footer site-footer-search">
  <nav class="footer-navigation">
    <ul>
      <li>
        <a href="/home/about">about leancook</a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leancook. What's in your fridge?</title>

  <link rel="icon" type="image/png" href="<%= asset_path 'favicon.png' %>" />

  <!-- OpenGraph Meta Tags -->
  <meta property="og:type" content="Website">
  <meta property="og:url" content="http://leancook.net" />
  <meta property="og:title" content="Leancook. What's in your fridge?" />
  <meta property="og:description" content="Look for recipes with your fridge ingredients." />
  <meta property="og:image" content="<%= asset_path 'slogan.png' %>" />

  <!-- Twitter Card Meta Tags -->
  <meta name="twitter:card" content="summary"/>
  <meta name="twitter:title" content="Leancook. What's in your fridge?"/>
  <meta name="twitter:description" content="Look for recipes with your fridge ingredients."/>
  <meta name="twitter:image" content="<%= asset_path 'slogan.png' %>"/>

  <!--<link href='http://fonts.googleapis.com/css?family=Merriweather:400,700' rel='stylesheet' type='text/css'>-->
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>
  <br/><br/>
<!-- Place this before your </body> tag. -->
    <script type="text/javascript">
      var rumbleBannerBackgroundColor, rumbleBannerTextColor, rumbleBannerLinkColor, rumbleBannerPlacement;
      rumbleBannerBackgroundColor = "#E32353";
      rumbleBannerTextColor = "#3C072E";
      rumbleBannerLinkColor = "#fff";
      rumbleBannerPlacement = "bottom"; // Optionally replace with "bottom".
    </script>
    <script src="https://d4nnn7wspfa3h.cloudfront.net/banner-2014.js" type="text/javascript"></script>
</body>
</html>